### ISSUE TITLE
PROJECT1: THREADS & PROJECT2: USER PROGRAMS 설정 및 수정

### ISSUE THREAD

**Issue by letsjo** [pintos-week3-4-team4/pintos_part2#1]
# PROJECT 1 : THREADS TEST
- [x] alarm-single
- [x] alarm-multiple
- [x] alarm-simultaneous
- [x] alarm-priority
- [x] alarm-zero
- [x] alarm-negative
- [x] priority-change
- [x] priority-donate-one
- [x] priority-donate-multiple
- [x] priority-donate-multiple2
- [x] priority-donate-nest
- [x] priority-donate-sema
- [x] priority-donate-lower
- [x] priority-donate-chain
- [x] priority-fifo
- [x] priority-preempt
- [x] priority-sema
- [x] priority-condvar
- [x] mlfqs-load-1
- [x] mlfqs-load-60
- [x] mlfqs-load-avg
- [x] mlfqs-recent-1
- [x] mlfqs-fair-2
- [x] mlfqs-fair-20
- [x] mlfqs-nice-2
- [ ] mlfqs-nice-10
- [x] mlfqs-block"

# PROJECT 2 : USER PROGRAMS TEST

- [x] priority-donate-chain
- [x] args-none
- [x] args-single
- [x] rgs-multiple
- [x] args-many
- [x] args-dbl-space
- [x] halt
- [x] exit
- [x] create-normal
- [x] create-empty
- [x] create-null
- [x] create-bad-ptr
- [x] create-long
- [x] create-exists
- [x] create-bound
- [x] open-normal
- [x] open-missing
- [x] open-boundary
- [x] open-empty
- [x] open-null
- [x] open-bad-ptr
- [x] open-twice
- [x] close-normal
- [x] close-twice
- [x] close-bad-fd
- [x] read-normal
- [x] read-bad-ptr
- [x] read-boundary
- [x] read-zero
- [x] read-stdout
- [x] read-bad-fd
- [x] write-normal
- [x] write-bad-ptr
- [x] write-boundary
- [x] write-zero
- [x] write-stdin
- [x] write-bad-fd
- [x] fork-once
- [x] fork-multiple
- [x] fork-recursive
- [x] fork-read
- [x] fork-close
- [x] fork-boundary
- [x] exec-once
- [x] exec-arg
- [x] exec-boundary
- [x] exec-missing
- [x] exec-bad-ptr
- [x] exec-read
- [x] wait-simple
- [x] wait-twice
- [x] wait-killed
- [x] wait-bad-pid
- [x] multi-recurse
- [x] multi-child-fd
- [x] rox-simple
- [x] rox-child
- [x] rox-multichild
- [x] bad-read
- [x] bad-write
- [x] bad-read2
- [x] bad-write2
- [x] bad-jump
- [x] bad-jump2
- [x] lg-create
- [x] lg-full
- [x] lg-random
- [x] lg-seq-block
- [x] lg-seq-random
- [x] sm-create
- [x] sm-full
- [x] sm-random
- [x] sm-seq-block
- [x] sm-seq-random
- [x] syn-read
- [x] syn-remove
- [x] syn-write
- [x] multi-oom
- [x] alarm-single
- [x] alarm-multiple
- [x] alarm-simultaneous
- [x] alarm-priority
- [x] alarm-zero
- [x] alarm-negative
- [x] priority-change
- [x] priority-donate-one
- [x] priority-donate-multiple
- [x] priority-donate-multiple2
- [x] priority-donate-nest
- [x] priority-donate-sema
- [x] priority-donate-lower
- [x] priority-fifo
- [x] priority-preempt
- [x] priority-sema
- [x] priority-condvar
- [x] priority-donate-chain
